# Отчет по лабораторной работе №3 на тему "NumPy"

**Выполнил**: студент 3 курса группы 12002408

Рыбин Даниил Евгеньевич

**Проверил**: ассистент кафедры информационных и робототехнических систем

Пузырев Никита Сергеевич

## Задания для выполнения

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

# Ход работы

In [2]:
import numpy as np
np.version.version

'2.1.3'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [16]:
array = np.random.randint(-10, 10, size = (10,10))
print(f"Массив: {array}")
min = array.min()
max = array.max()
print(f"Минимум: {min}")
print(f"Максимум: {max}")

Массив: [[ -7  -7  -4  -7  -6   2   8 -10   0  -8]
 [  7   9   4 -10  -2   2  -6   7  -5   6]
 [ -9   9   0 -10   4   1   1  -8 -10   5]
 [-10   5   6  -7  -4  -6   6  -9  -3  -9]
 [  1   3   0  -3 -10  -8   0  -6  -7  -5]
 [  7 -10   5  -6  -2  -5   8   4  -6  -1]
 [  4  -6 -10  -3   3   6   6   0   2 -10]
 [ -7  -6  -8   2   6  -8  -8  -7   0 -10]
 [ -1   9  -9   1  -5   1   6  -5   7   1]
 [  6   3   3  -8  -6  -4  -7  -9  -5 -10]]
Минимум: -10
Максимум: 9


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [19]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [21]:
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее значение строки матрицы и вычесть его из каждого элемента строки

In [27]:
z = np.random.rand(5, 10)
print("Исходная матрица:", z)
row_means = z.mean(axis=1)
print("\nСредние значения строк:", row_means)
mat = z - row_means[:, np.newaxis]
print("\nМатрица после вычитания:\n", mat)

Исходная матрица: [[0.73609288 0.71830186 0.98526609 0.51244502 0.59285497 0.14951198
  0.04440383 0.0481462  0.14158767 0.10090566]
 [0.98425689 0.33806431 0.3756594  0.79546484 0.6153087  0.83725356
  0.66930428 0.30635255 0.42356322 0.74363095]
 [0.52373549 0.25145851 0.78433791 0.99112075 0.28785095 0.80230199
  0.02122521 0.64903055 0.17570392 0.43253718]
 [0.28166441 0.35352172 0.46576788 0.95870161 0.91354351 0.17097527
  0.09823306 0.52795344 0.59190365 0.46483478]
 [0.15979802 0.14758417 0.57741697 0.25905705 0.06141994 0.17514553
  0.08741714 0.67163887 0.55957726 0.73272695]]

Средние значения строк: [0.40295162 0.60888587 0.49193025 0.48270993 0.34317819]

Матрица после вычитания:
 [[ 0.33314126  0.31535025  0.58231448  0.10949341  0.18990336 -0.25343964
  -0.35854779 -0.35480542 -0.26136395 -0.30204596]
 [ 0.37537102 -0.27082156 -0.23322647  0.18657897  0.00642283  0.22836769
   0.06041841 -0.30253331 -0.18532265  0.13474508]
 [ 0.03180525 -0.24047173  0.29240766  0.499190

5. Поменяйте 1 и 2 строки матрицы

In [28]:
z = np.arange(25).reshape(5, 5)
print("До:\n", z)
z[[0, 1]] = z[[1, 0]]
print("\nПосле:\n", z)

До:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

После:
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 представляющий собой точки в декартовой системе координат, преобразовать в полярную

In [30]:
import numpy as np
z = np.random.random((10, 2))
X, Y = z[:, 0], z[:, 1]
R = np.hypot(X, Y)
T = np.arctan2(Y, X)
polar = np.column_stack((R, T))

print("Декартовы координаты:\n", z)
print("\nПолярные координаты:\n", polar)

Декартовы координаты:
 [[0.06560785 0.18364365]
 [0.30738249 0.6803497 ]
 [0.88438803 0.05308014]
 [0.66185063 0.3964949 ]
 [0.85280439 0.66360406]
 [0.68137482 0.14268687]
 [0.40259269 0.89646074]
 [0.99582922 0.33128549]
 [0.73534573 0.22027122]
 [0.98381207 0.52823017]]

Полярные координаты:
 [[0.19501123 1.22767178]
 [0.74656527 1.14644592]
 [0.88597951 0.05994714]
 [0.77152736 0.53973544]
 [1.08057654 0.6612709 ]
 [0.69615457 0.20642728]
 [0.98271192 1.14869836]
 [1.04948841 0.32115613]
 [0.76762801 0.2910419 ]
 [1.11665273 0.49274697]]


7. Заменить максимальный элемент массива на ноль

In [36]:
z = np.random.random(10)
print("Исходный массив:\n", z)
print("\nМаксимальный элемент: ", z.max())
z[z.argmax()] = 0
print("\nПосле замены:\n", z)

Исходный массив:
 [0.36720268 0.38215969 0.95736264 0.62332563 0.85896741 0.82352279
 0.65357002 0.53778631 0.48519228 0.25673973]

Максимальный элемент:  0.9573626394256939

После замены:
 [0.36720268 0.38215969 0.         0.62332563 0.85896741 0.82352279
 0.65357002 0.53778631 0.48519228 0.25673973]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
# Напишите ваш код здесь

9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
z = np.array([1,2,3,4,5])
# Напишите ваш код здесь

10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
# Напишите ваш код здесь

## Вывод

В результате выполнения лабораторной работы были изучены основные операции в Python, а также решены задачи в LeetCode.


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?