# Отчет по лабораторной работе №3 на тему "NumPy"

**Выполнил**: студент 3 курса группы 12002408

Рыбин Даниил Евгеньевич

**Проверил**: ассистент кафедры информационных и робототехнических систем

Пузырев Никита Сергеевич

## Задания для выполнения

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

# Ход работы

In [ ]:
import numpy as np
np.version.version

'2.1.3'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [ ]:
array = np.random.randint(-10, 10, size = (10,10))
print(f"Массив: {array}")
min = array.min()
max = array.max()
print(f"Минимум: {min}")
print(f"Максимум: {max}")

Массив: [[ -5  -2   2   6 -10   9  -8   0   3   7]
 [ -4  -1   4   2   7  -3   7   7   3  -1]
 [ -8   7 -10   0 -10   2   6   9   0  -4]
 [ -6  -9 -10  -5   6 -10  -8  -9  -8  -3]
 [ -2  -5   3  -5   8   4   1   4   3  -9]
 [  7   3   1   4   5   2   8  -7  -1   5]
 [ -3 -10   9  -9  -6  -3   5   1  -3  -4]
 [  1   4  -8  -4  -5   8   2  -2   3  -8]
 [ -2  -3   5   5  -1   7  -2 -10   5   3]
 [ -1 -10  -6  -9  -3  -1  -5   4   6   9]]
Минимум: -10
Максимум: 9


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [8]:
matrix = np.ones((8, 8), dtype=int)
matrix[1::2, ::2] = 0
matrix[::2, 1::2] = 0
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее значение строки матрицы и вычесть его из каждого элемента строки

In [ ]:
z = np.random.rand(5, 10)
print("Исходная матрица:", z)
row_means = z.mean(axis=1)
print("\nСредние значения строк:", row_means)
mat = z - row_means[:, np.newaxis]
print("\nМатрица после вычитания:\n", mat)

Исходная матрица: [[9.30386688e-01 6.70549004e-01 2.62049109e-01 7.30090858e-01
  2.74312287e-01 9.01885215e-01 2.03871479e-01 5.44763052e-01
  6.89739491e-01 2.23162109e-01]
 [1.91443164e-01 7.30497095e-01 7.24403120e-01 2.70182811e-01
  3.06607416e-01 5.57568196e-01 1.22462742e-01 1.07765937e-01
  8.55420684e-01 9.62181736e-01]
 [1.00238495e-01 8.25955370e-01 9.51259729e-01 2.96085521e-02
  5.82478276e-01 7.32866304e-01 7.29365422e-01 2.46042161e-04
  9.58622839e-01 5.39691049e-01]
 [1.23009711e-02 8.65669913e-01 5.85783795e-01 1.32898653e-01
  4.83424066e-01 5.78192089e-02 9.70308659e-01 1.43483949e-01
  5.03813947e-01 7.01093718e-01]
 [2.57662495e-01 3.75737183e-01 7.76641973e-01 7.61746076e-01
  1.58039167e-01 9.07809834e-03 9.78256309e-01 8.64212975e-01
  6.82913049e-01 7.70111350e-01]]

Средние значения строк: [0.54308093 0.48285329 0.54503321 0.44565969 0.56343987]

Матрица после вычитания:
 [[ 0.38730576  0.12746807 -0.28103182  0.18700993 -0.26876864  0.35880429
  -0.33920945

5. Поменяйте 1 и 2 строки матрицы

In [ ]:
z = np.arange(25).reshape(5, 5)
print("До:\n", z)
z[[0, 1]] = z[[1, 0]]
print("\nПосле:\n", z)

До:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

После:
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 представляющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
import numpy as np
z = np.random.random((10, 2))
X, Y = z[:, 0], z[:, 1]
R = np.hypot(X, Y)
T = np.arctan2(Y, X)
polar = np.column_stack((R, T))

print("Декартовы координаты:\n", z)
print("\nПолярные координаты:\n", polar)

Декартовы координаты:
 [[0.60656884 0.62559244]
 [0.51428519 0.08039036]
 [0.35331353 0.35442874]
 [0.33415868 0.6091498 ]
 [0.35957995 0.09494645]
 [0.59021801 0.98180154]
 [0.96166387 0.43800471]
 [0.91677881 0.24499037]
 [0.44812356 0.51453783]
 [0.79193132 0.69655692]]

Полярные координаты:
 [[0.87137343 0.80083615]
 [0.52053038 0.15505995]
 [0.50044998 0.78697389]
 [0.6947845  1.06905498]
 [0.37190398 0.2581562 ]
 [1.14555295 1.02952567]
 [1.0567145  0.42738972]
 [0.94894871 0.26112781]
 [0.68232243 0.85427929]
 [1.05467851 0.72141096]]


7. Заменить максимальный элемент массива на ноль

In [ ]:
z = np.random.random(10)
print("Исходный массив:\n", z)
print("\nМаксимальный элемент: ", z.max())
z[z.argmax()] = 0
print("\nПосле замены:\n", z)

Исходный массив:
 [0.25821273 0.91833111 0.68236474 0.43412265 0.45987002 0.84265012
 0.05629904 0.45333737 0.79562258 0.64115244]

Максимальный элемент:  0.9183311058444805

После замены:
 [0.25821273 0.         0.68236474 0.43412265 0.45987002 0.84265012
 0.05629904 0.45333737 0.79562258 0.64115244]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производится только 1 раз

In [ ]:
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
print("Индексы:\n", i)
z[np.unique(i)] += 1
print("\nИтоговый массив:\n", z)

Индексы:
 [9 1 7 7 6 5 1 9 7 4 5 5 0 1 4 8 7 4 1 3]

Итоговый массив:
 [2. 2. 1. 2. 2. 2. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
z = np.array([1, 2, 3, 4, 5])
k = 3
new_len = len(z) + (len(z) - 1) * k
result = np.zeros(new_len, dtype=z.dtype)
result[::k + 1] = z
print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
z = np.arange(100)
v = np.random.uniform(0, 100)
index = np.abs(z - v).argmin()
closest_value = z[index]
print(f"Искомое значение: {v:.4f}")
print(f"Ближайший элемент: {closest_value} (на индексе {index})")

Искомое значение: 26.4136
Ближайший элемент: 26 (на индексе 26)


## Вывод

В результате выполнения лабораторной работы были освоены механизмы работы с библиотекой NumPy для языка Python.


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3]) #int32/int64
np.array([1., 4, 2, 5, 3]) #float64
np.array([1, 4, 2, 5, 3], dtype='float128') #float128
np.array([1., 4, 2, 5, 3], dtype='complex128') #complex128
np.array([1, 4, 2, 5, 3], dtype ='float64') #float64
np.array([1, 4, 2, 5, 3], dtype =int64) #NameError
np.array([1, 4, 2, 5, 3], dtype='bool') #bool
np.array([1, 4, 2, 5, 3], dtype='str') #str
np.array([1, 4, 2, 5, '3']) #str
np.array([1, -4, 2, 0, 1j]) #complex128
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1' #41
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1] #-4
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1] #False
np.array([1, -4, 2, 0, True], dtype='int64')[-1] #1
np.array([1, -4, 2, 0, 1j], dtype='int64')[1] #TypeError
np.array([1, -4, 2, 0, 1j], dtype='str')[-1] #1j
np.array([1, 4, 2, 5, '3'])[-1] * 3 #333
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
#array([[1., 1., 1., 1., 1.],
     #  [1., 1., 1., 1., 1.],
     #  [1., 1., 1., 1., 1.]])

np.full((3, 5), 3.14)
#array([[3.14, 3.14, 3.14, 3.14, 3.14],
     #  [3.14, 3.14, 3.14, 3.14, 3.14],
     #  [3.14, 3.14, 3.14, 3.14, 3.14]])

np.linspace(0, 1, 5)
#array([0.  , 0.25, 0.5 , 0.75, 1.  ])

np.diag((1,3,5))
#array([[1, 0, 0],
      # [0, 3, 0],
      # [0, 0, 5]])

np.smile((1,3,5))#AttributeError

np.random.random((3, 3))
# Значения будут случайными

np.eye(3)
#array([[1., 0., 0.],
      # [0., 1., 0.],
      # [0., 0., 1.]])

np.empty(3) #Выделяет в памяти массив длины 3 без инициализации.
```


**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различие между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
#Различие — в направлении разреза (по строкам или по столбцам):
# np.split(grid, [2]) - режет матрицу по горизонтали
# np.split(grid, [2], axis=1) - режет матрицу по вертикали
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
# Различие — в операции сложения:
# [1, 2, 3] + [3, 2, 1] - выполняет склеивание. В результате получается один список из 6 элементов.
# np.array([1, 2, 3]) + np.array([3, 2, 1]) - складываются числа, стоящие на одинаковых позициях.
```

**7**. Как в CodeLab измерить время выполнения кода?

С помощью встроенных IPython-команд:
%time - однократный замер времени выполнения одной строки.
%%time - однократный замер времени выполнения всей ячейки.

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M) #59
np.sum(M, axis=1) #array([14, 29, 21])
np.sum(M, axis=0) #array([11, 17, 17, 19])
np.sum(M, axis=2) #AxisError
np.sum(M, 1) #array([14, 29, 21])
sum(M)#array([11, 17, 17, 19])
sum(M,1)#ValueError
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3 #array([False, False, False,  True])
X < 3 #array([ True,  True, False, False])
X[X < 3]#array([1, 2])
X[X > 3]#array([4])
X[X != 3]#array([1, 2, 4])
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

**Преимущества**: быстрее в сотни раз, занимают меньше памяти.

**Причины**:

Непрерывная память - данные кэшируются процессором), не в виде разрозненных указателей.

Один тип данных (dtype) - нет расходов на динамическую типизацию и проверку типов на каждом шаге.

Вычисления идут на скомпилированном C-коде с использованием векторных инструкций процессора.